title: Biased Movie Thoughts
author: Alex and Brandon Walker
email: biasedmoviethoughts@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Description in progress...

twitter_username: jekyllrb
github_username:  jekyll

# Google Analytics
google_analytics: UA-102271247-1

# Number of pages
paginate: 5

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
# - about.md
 - trailers/trailers.md
 - archive.md

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock

# Automatically Generate Sitemap (sitemap.xml)
gems:
  - jekyll-sitemap
  - jekyll-paginate
